### ISSUE TITLE
Player mechanics

### ISSUE THREAD

**Issue by diguifi** [game-devs/pique-catch#2]
- Properties
- Methods
- Collision checking

**Comment by leoddias** [comment]
Added collision with platforms at [this commit](https://github.com/game-devs/pique-catch/commit/6bdb3e05d34af1335d5d0f4e4df15fc49ecfee9b)

**Comment by leoddias** [comment]
Add collision with platforms at [this commit](https://github.com/game-devs/pique-catch/commit/6bdb3e05d34af1335d5d0f4e4df15fc49ecfee9b)
