### ISSUE TITLE
Game mechanics and refactoring

### ISSUE THREAD

**Issue by diguifi** [game-devs/pique-catch#4]
- [x] When timer hits 0, runner gets 1 point
- [x] When the item is taken, reset timer
- [ ] Random positions for item
- [x] Insert players into Sprite Group

**Comment by leoddias** [comment]
Most of those tasks was finished in [https://github.com/game-devs/pique-catch/pull/7](this pull request), the only one that couldn't be done was "Random positions for item", because we need to finish issue-3 first.
